import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "../component/Header";
import { Roboto } from 'next/font/google'
import Footer from "../component/Footer"
const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
console.log(roboto)
export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={roboto.className}>
      <body>
      <Header/>
        {children}
        <Footer/>
        </body>
    </html>
  );
}
